# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9nm2wvNWpp8yv8dATF8qAw0hnoKkDyR
"""

import pandas as pd

data_full = pd.read_csv('movies.csv')
data = data_full[['budget','revenue']]

data.head()

print('isnull:\n ',data.isnull().sum())
print('\nisna:\n ', data.isna().sum())

import matplotlib.pyplot as plt

plt.scatter(data['budget'], data['revenue'], color= "blue")
plt.title('Budget vs Revenue')
plt.xlabel('Budget')
plt.ylabel('Revenue')
plt.show()

from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LinearRegression

train_set, test_set = train_test_split(data, test_size=0.2, random_state=42)
train_x = np.array(train_set['budget'])
train_y = np.array(train_set['revenue'])
test_x = np.array(test_set['budget'])
test_y = np.array(test_set['revenue'])

model = LinearRegression()


model.fit(train_x.reshape(-1,1), train_y)

print('coefficients : ', model.coef_)
print('intercept :', model.intercept_)

plt.scatter(train_x, train_y, color= "blue")
plt.plot(train_x, model.coef_*train_x + model.intercept_, color= "red")

predicted_y = model.predict(test_x.reshape(-1,1))

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, root_mean_squared_error

mae = mean_absolute_error(test_y, predicted_y)
mse = mean_squared_error(test_y, predicted_y)
rmse = root_mean_squared_error(test_y, predicted_y)
r2 = r2_score(test_y, predicted_y)

print('MAE: ', mae)
print('MSE: ', mse)
print('RMSE: ', rmse)
print('R2: ', r2)